sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - mysql-server
      - php7.1-cli
      - php7.1-mysqli

services:
  - mysql

stages:
  - test
  # - deploy

language: node_js
node_js: 10

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - npm install
  - lix install haxe $HAXE_VERSION
  - lix download

  
script:
  - lix run travix node
  - lix run travix neko
  - lix run travix run php7

# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       os: linux
#       install:
#         - npm i -g lix
#         - lix download
#       script: skip
#       env:
#         secure: xxxxxxxx
#       after_success:
#         - lix run travix install
#         - lix run travix release
