sudo: required
dist: xenial

services:
  - mysql

services:
  - mysql

stages:
  - test

language: node_js
node_js: 10

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - npm install
  - lix install haxe $HAXE_VERSION
  - lix download

  
script:
  - lix run travix node
  - lix run travix neko
  - lix run travix php7