name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
      
        haxe-version:
          - 4.0.5
          - 4.1.5
          - stable
          - nightly
        target: 
          - node
          - php
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: |
        sudo apt update -qqy
        sudo apt install -qqy php-cli php-mbstring php-xml php-mysql
      if: ${{ matrix.target == 'php' }}
    - run: npm i
    - run: npm run test ${{ matrix.target }}