name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        haxe-version:
          - stable
          - nightly
        target: 
          - node
          - php
    steps:
    - uses: actions/checkout@v2
    - uses: lix-pm/setup-lix@master
    - uses: actions/setup-node@v1
    - run: npm i
    - run: lix install haxe ${{ matrix.haxe-version }}
    - run: lix download
    - run: lix run travix ${{ matrix.target }}